service: guru-crud-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DYNAMODB_GURU_TABLE: ${self:service}-GuruTable-${sls:stage}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-GuruTable-${sls:stage}

functions:
  createGuru:
    handler: createGuru.createGuru
    events:
      - httpApi:
          path: /
          method: post
  getGurus:
    handler: getGurus.getGurus
    events:
      - httpApi:
          path: /
          method: get
  getGuru:
    handler: getGuru.getGuru
    events:
      - httpApi:
          path: /{name}
          method: get
  deleteGuru:
    handler: deleteGuru.deleteGuru
    events:
      - httpApi:
          path: /{name}
          method: delete
  updateGuru:
    handler: updateGuru.updateGuru
    events:
      - httpApi:
          path: /{name}
          method: put
    


resources:
  Resources:
    GuruTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-GuruTable-${sls:stage}

