

name: Deploy API (dev)

# Triggers
on:
  push:
    branches:
      - main

# Specify what jobs to run
jobs:
  sls_deploy_dev:
    name: deploy (dev)
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v1 

      # Install npm and it's dependencies
      - name: Install npm dependencies
        run: npm install

      - name: serverless deploy (dev)
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./guru-crud-api && serverless deploy --stage dev"
          entrypoint: /bin/sh
